language: ruby
sudo: false
bundler_args: "--retry=3 --jobs=3"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  slack:
    secure: B25UgGnWzd/gLr97Ac233rhp7bV3FnmbmuYU9KGLa7s8YTmdKnHg5ASOl3NEdDRSZwhhQvMF6FRhqLvQenFsIYn9f9qSmY0+d5/gB8iUQkGAIXIx0VFrPhO6ZTefEJ2uhPyKtZIkzEOVD9jo4w5Kh9XvUPFY1v8OM+wz+8cW28G+fS1gof+yJUBVQb7/FGSzc2nxDvCwcU2pYeQ2rUnugDc8wfcQYCsp+MU+qBTsotTBCiGqrZWouqi3dWbMPHqeaW8B343+jviM0LgvyEF6klw0dR218SRWlavYjZq6w4yEwtPI+Wl0jXe06DcbISBQwKRH4ljwT2Qvx0gjIEG9fKo7Gl59gg/U3p3wZixV/O1/f0oDgVO1FZIMHP0CVWX8+VV/g4ru/jVp0R74Mfq3mIhSh1z7iMgFMoVMzOLJq8nDPQWPi+1Wc5z1AeCnC1bjcwhN07FzIHq3GTuqjLGRNfm5nvG8PCsw0dgsV9z826teHJrXJz8mApGZZR6WvWdSqWdUaIxtHoeuaBd+7/iqxYKdW8uov4U7Vc4gFqs36SmNtrRf1fnVs/p0QM4SbPo+KYROin7oZTngMLVJ2qLYhTMWpszJfnpFl2ZHYlfTF2rHUaBioOnagAqs1iiVp51mX2brXnjUdQWGbGuEryrO88qZ5tS6DnfS4+A57cgloe8=
